sudo: false
language: rust
dist: trusty
rust:
  - nightly
  - beta
  - stable
  - 1.20.0 # minimum supported version
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo install clippy;
    fi
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo clippy;
    fi
